#include "Cards.h"

#include <random>

const CardData AllCards[] = {
	{}, // Unknown,
	{ CardType::Spell, 0, "The Coin", 0, 0 },

	// 1-mana neutral cards
	{ CardType::Minion, 0, "", 0, 0 }, // Wisp
	{ CardType::Minion, 0, "Abusive Sergeant", 0, 0 },
	{ CardType::Minion, 0, "Angry Chicken", 0, 0 },
	{ CardType::Minion, 0, "Bloodsail Corsair", 0, 0 },
	{ CardType::Minion, 0, "Elven Archer", 0, 0 },
	{ CardType::Minion, 0, "Goldshire Footman", 0, 0 },
	{ CardType::Minion, 0, "Grimscale Oracle", 0, 0 },
	{ CardType::Minion, 0, "Hungry Crab", 0, 0 },
	{ CardType::Minion, 0, "Leper Gnome", 0, 0 },
	{ CardType::Minion, 0, "Lightwarden", 0, 0 },
	{ CardType::Minion, 1, "Murloc Raider", 2, 1 },
	{ CardType::Minion, 0, "Murloc Tidecaller", 0, 0 },
	{ CardType::Minion, 0, "Secretkeeper", 0, 0 },
	{ CardType::Minion, 0, "Shieldbearer", 0, 0 },
	{ CardType::Minion, 0, "Southsea Deckhand", 0, 0 },
	{ CardType::Minion, 0, "Stonetusk Boar", 0, 0 },
	{ CardType::Minion, 0, "Undertaker ", 0, 0 },
	{ CardType::Minion, 0, "Voodoo Doctor", 0, 0 },
	{ CardType::Minion, 0, "Worgen Infiltrator", 0, 0 },
	{ CardType::Minion, 0, "Young Dragonhawk", 0, 0 },
	{ CardType::Minion, 0, "Young Priestess", 0, 0 },
	{ CardType::Minion, 0, "Zombie Chow", 0, 0 },

	// 2-mana neutral cards
	{ CardType::Minion, 0, "AcidicSwampOoze", 0, 0 },
	{ CardType::Minion, 0, "AmaniBerserker", 0, 0 },
	{ CardType::Minion, 0, "AncientWatcher", 0, 0 },
	{ CardType::Minion, 2, "Bloodfen Raptor", 3, 2 },
	{ CardType::Minion, 0, "BloodmageThalnos", 0, 0 },
	{ CardType::Minion, 0, "BloodsailRaider", 0, 0 },
	{ CardType::Minion, 0, "BluegillWarrior", 0, 0 },
	{ CardType::Minion, 0, "CaptainsParrot", 0, 0 },
	{ CardType::Minion, 0, "CrazedAlchemist", 0, 0 },
	{ CardType::Minion, 0, "DireWolfAlpha", 0, 0 },
	{ CardType::Minion, 0, "Doomsayer", 0, 0 },
	{ CardType::Minion, 0, "EchoingOoze", 0, 0 },
	{ CardType::Minion, 0, "FaerieDragon", 0, 0 },
	{ CardType::Minion, 0, "FrostwolfGrunt", 0, 0 },
	{ CardType::Minion, 0, "HauntedCreeper", 0, 0 },
	{ CardType::Minion, 0, "IronbeakOwl", 0, 0 },
	{ CardType::Minion, 0, "KnifeJuggler", 0, 0 },
	{ CardType::Minion, 0, "KoboldGeomancer", 0, 0 },
	{ CardType::Minion, 0, "LootHoarder", 0, 0 },
	{ CardType::Minion, 0, "LorewalkerCho", 0, 0 },
	{ CardType::Minion, 0, "MadBomber", 0, 0 },
	{ CardType::Minion, 0, "MadScientist", 0, 0 },
	{ CardType::Minion, 0, "ManaAddict", 0, 0 },
	{ CardType::Minion, 0, "ManaWraith", 0, 0 },
	{ CardType::Minion, 0, "MasterSwordsmith", 0, 0 },
	{ CardType::Minion, 0, "MillhouseManastorm", 0, 0 },
	{ CardType::Minion, 0, "MurlocTidehunter", 0, 0 },
	{ CardType::Minion, 0, "NatPagle", 0, 0 },
	{ CardType::Minion, 0, "NerubarWeblord", 0, 0 },
	{ CardType::Minion, 0, "NerubianEgg", 0, 0 },
	{ CardType::Minion, 0, "NoviceEngineer", 0, 0 },
	{ CardType::Minion, 0, "PintSizedSummoner", 0, 0 },
	{ CardType::Minion, 2, "River Crocolisk", 2, 3 },
	{ CardType::Minion, 0, "SunfuryProtector", 0, 0 },
	{ CardType::Minion, 0, "UnstableGhoul", 0, 0 },
	{ CardType::Minion, 0, "WildPyromancer", 0, 0 },
	{ CardType::Minion, 0, "YouthfulBrewmaster", 0, 0 },

	// 3-mana neutral cards
	{ CardType::Minion, 0, "AcolyteOfPain", 0, 0 },
	{ CardType::Minion, 0, "AlarmoBot", 0, 0 },
	{ CardType::Minion, 0, "ArcaneGolem", 0, 0 },
	{ CardType::Minion, 0, "BigGameHunter", 0, 0 },
	{ CardType::Minion, 0, "BloodKnight", 0, 0 },
	{ CardType::Minion, 0, "ColdlightOracle", 0, 0 },
	{ CardType::Minion, 0, "ColdlightSeer", 0, 0 },
	{ CardType::Minion, 0, "DalaranMage", 0, 0 },
	{ CardType::Minion, 0, "DancingSwords", 0, 0 },
	{ CardType::Minion, 0, "Deathlord", 0, 0 },
	{ CardType::Minion, 0, "Demolisher", 0, 0 },
	{ CardType::Minion, 0, "EarthenRingFarseer", 0, 0 },
	{ CardType::Minion, 0, "EmperorCobra", 0, 0 },
	{ CardType::Minion, 0, "FlesheatingGhoul", 0, 0 },
	{ CardType::Minion, 0, "HarvestGolem", 0, 0 },
	{ CardType::Minion, 0, "ImpMaster", 0, 0 },
	{ CardType::Minion, 0, "InjuredBlademaster", 0, 0 },
	{ CardType::Minion, 0, "IronforgeRifleman", 0, 0 },
	{ CardType::Minion, 0, "IronfurGrizzly", 0, 0 },
	{ CardType::Minion, 0, "JunglePanther", 0, 0 },
	{ CardType::Minion, 0, "KingMukla", 0, 0 },
	{ CardType::Minion, 3, "Magma Rager", 5, 1 },
	{ CardType::Minion, 0, "MindControlTech", 0, 0 },
	{ CardType::Minion, 0, "MurlocWarleader", 0, 0 },
	{ CardType::Minion, 0, "QuestingAdventurer", 0, 0 },
	{ CardType::Minion, 0, "RagingWorgen", 0, 0 },
	{ CardType::Minion, 0, "RaidLeader", 0, 0 },
	{ CardType::Minion, 0, "RazorfenHunter", 0, 0 },
	{ CardType::Minion, 0, "ScarletCrusader", 0, 0 },
	{ CardType::Minion, 0, "ShadeOfNaxxramas", 0, 0 },
	{ CardType::Minion, 0, "ShatteredSunCleric", 0, 0 },
	{ CardType::Minion, 0, "SilverbackPatriarch", 0, 0 },
	{ CardType::Minion, 0, "SouthseaCaptain", 0, 0 },
	{ CardType::Minion, 0, "StoneskinGargoyle", 0, 0 },
	{ CardType::Minion, 0, "TaurenWarrior", 0, 0 },
	{ CardType::Minion, 0, "ThrallmarFarseer", 0, 0 },
	{ CardType::Minion, 0, "TinkmasterOverspark", 0, 0 },
	{ CardType::Minion, 0, "Wolfrider", 0, 0 },

	// 4-mana neutral cards
	{ CardType::Minion, 0, "AncientBrewmaster", 0, 0 },
	{ CardType::Minion, 0, "AncientMage", 0, 0 },
	{ CardType::Minion, 0, "BaronRiverdare", 0, 0 },
	{ CardType::Minion, 4, "Chillwind Yeti", 4, 5 },
	{ CardType::Minion, 0, "CultMaster", 0, 0 },
	{ CardType::Minion, 0, "DarkIronDwarf", 0, 0 },
	{ CardType::Minion, 0, "DefenderOfArgus", 0, 0 },
	{ CardType::Minion, 0, "DragonlingMechanic", 0, 0 },
	{ CardType::Minion, 0, "DreadCorsair", 0, 0 },
	{ CardType::Minion, 0, "GnomishInventor", 0, 0 },
	{ CardType::Minion, 0, "LeeroyJenkins", 0, 0 },
	{ CardType::Minion, 0, "MogushanWarden", 0, 0 },
	{ CardType::Minion, 4, "Oasis Snapjaw", 2, 7 },
	{ CardType::Minion, 0, "OgreMagi", 0, 0 },
	{ CardType::Minion, 0, "OldMurkEye", 0, 0 },
	{ CardType::Minion, 0, "SenjinShieldMasta", 0, 0 },
	{ CardType::Minion, 0, "SilvermoonGuardian", 0, 0 },
	{ CardType::Minion, 0, "Spellbreaker", 0, 0 },
	{ CardType::Minion, 0, "StormwindKnight", 0, 0 },
	{ CardType::Minion, 0, "TwilightDrake", 0, 0 },
	{ CardType::Minion, 0, "VioletTeacher", 0, 0 },
	{ CardType::Minion, 0, "WailingSoul", 0, 0 },

	// 5-mana neutral cards
	{ CardType::Minion, 0, "Abomination", 0, 0 },
	{ CardType::Minion, 0, "AzureDrake", 0, 0 },
	{ CardType::Minion, 0, "BootyBayBodyguard", 0, 0 },
	{ CardType::Minion, 0, "CaptainGreenskin", 0, 0 },
	{ CardType::Minion, 0, "DarkscaleHealer", 0, 0 },
	{ CardType::Minion, 0, "EliteTaurenChieftan", 0, 0 },
	{ CardType::Minion, 0, "FacelessManipulator", 0, 0 },
	{ CardType::Minion, 0, "FenCreeper", 0, 0 },
	{ CardType::Minion, 0, "Feugen", 0, 0 },
	{ CardType::Minion, 0, "FrostwolfWarlord", 0, 0 },
	{ CardType::Minion, 0, "GadgetzanAuctioneer", 0, 0 },
	{ CardType::Minion, 0, "GurubashiBerserker", 0, 0 },
	{ CardType::Minion, 0, "HarrisonJones", 0, 0 },
	{ CardType::Minion, 0, "Loatheb", 0, 0 },
	{ CardType::Minion, 0, "Nightblade", 0, 0 },
	{ CardType::Minion, 0, "SilverhandKnight", 0, 0 },
	{ CardType::Minion, 0, "SludgeBelcher", 0, 0 },
	{ CardType::Minion, 0, "SpectralKnight", 0, 0 },
	{ CardType::Minion, 0, "SpitefulSmith", 0, 0 },
	{ CardType::Minion, 0, "Stalaag", 0, 0 },
	{ CardType::Minion, 0, "StampedingKodo", 0, 0 },
	{ CardType::Minion, 0, "StormpikeCommando", 0, 0 },
	{ CardType::Minion, 0, "StranglethornTiger", 0, 0 },
	{ CardType::Minion, 0, "VentureCoMercenary", 0, 0 },

	// 6-mana neutral cards
	{ CardType::Minion, 0, "Archmage", 0, 0 },
	{ CardType::Minion, 0, "ArgentCommander", 0, 0 },
	{ CardType::Minion, 6, "Boulderfist Ogre", 6, 7 },
	{ CardType::Minion, 0, "CairneBloodhoof", 0, 0 },
	{ CardType::Minion, 0, "FrostElemental", 0, 0 },
	{ CardType::Minion, 0, "GelbinMekkatorque", 0, 0 },
	{ CardType::Minion, 0, "Hogger", 0, 0 },
	{ CardType::Minion, 0, "IllidanStormrage", 0, 0 },
	{ CardType::Minion, 0, "LordOfTheArena", 0, 0 },
	{ CardType::Minion, 0, "Maexxna", 0, 0 },
	{ CardType::Minion, 0, "PriestessOfElune", 0, 0 },
	{ CardType::Minion, 0, "RecklessRocketeer", 0, 0 },
	{ CardType::Minion, 0, "Sunwalker", 0, 0 },
	{ CardType::Minion, 0, "SylvanasWindrunner", 0, 0 },
	{ CardType::Minion, 0, "TheBeast", 0, 0 },
	{ CardType::Minion, 0, "TheBlackKnight", 0, 0 },
	{ CardType::Minion, 0, "WindfuryHarpy", 0, 0 },

	// 7-mana neutral cards
	{ CardType::Minion, 0, "BaronGeddon", 0, 0 },
	{ CardType::Minion, 7, "Core Hound", 9, 5 },
	{ CardType::Minion, 0, "RavenholdtAssassin", 0, 0 },
	{ CardType::Minion, 0, "StormwindChampion", 0, 0 },
	{ CardType::Minion, 7, "War Golem", 7, 7 },

	// 8-mana neutral cards
	{ CardType::Minion, 0, "Gruul", 0, 0 },
	{ CardType::Minion, 0, "KelThuzad", 0, 0 },
	{ CardType::Minion, 0, "RagnarosTheFirelord", 0, 0 },

	// 9-mana neutral cards
	{ CardType::Minion, 0, "Alexstrasza", 0, 0 },
	{ CardType::Minion, 0, "Malygos", 0, 0 },
	{ CardType::Minion, 0, "Nozdormu", 0, 0 },
	{ CardType::Minion, 0, "Onyxia", 0, 0 },
	{ CardType::Minion, 0, "Ysera", 0, 0 },

	// 10-mana neutral cards
	{ CardType::Minion, 0, "Deathwing", 0, 0 },
	{ CardType::Minion, 0, "SeaGiant", 0, 0 },

	// 12-mana neutral cards
	{ CardType::Minion, 0, "MountainGiant", 0, 0 },

	// 20-mana neutral cards
	{ CardType::Minion, 0, "MoltenGiant", 0, 0 }

};

const CardData* GetCardData(Card c)
{
	return &AllCards[(unsigned)c];
}

const std::vector<Card> DeckPossibleCards = {
	Card::MurlocRaider,
	Card::RiverCrocolisk,
	Card::BloodfenRaptor,
	Card::MagmaRager,
	Card::ChillwindYeti,
	Card::OasisSnapjaw,
	Card::BoulderfistOgre,
	Card::WarGolem,
	Card::CoreHound,
};